additional:
- "test-template-repository-sync"
files:
  - ".gitignore"  # include
  - "test_sync_file.txt" #include
  - "!README.md" # exclude
   # you probably want to exclude these files:
  - "!.github/workflows/template-sync.yml"
  - "!.github/template-sync.yml"
